package com.catshi.core.exceptions

class UserAlreadyExistsException : Throwable() {
}